apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: frontend

spec:
  containers:
  - name: app-v1
    image: nginx
  - name: postgres
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       value: mypassword
     
