apiVersion: v1
kind: Secret
metadata:
  name: my-secret

data:
  USR_NAME: dmluYXk=
  PASS: dmluYXk=

#kubectl create -f secret_data.yaml
#To call this in Pod def.
# Under spec: 
#          containers: 
#               envFrom: 
#               - secretRef:
#                     name: my-secret
#
#